In [6]:
pip install --user -U nltk

distutils: /Users/juliette/Library/Python/3.9/lib/python/site-packages
sysconfig: /Users/juliette/Library/Python/3.9/lib/python3.9/site-packages
distutils: /Users/juliette/Library/Python/3.9/lib/python/site-packages
sysconfig: /Users/juliette/Library/Python/3.9/lib/python3.9/site-packages
user = True
home = None
root = None
prefix = None
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.3.2/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install gensim

     |████████████████████████████████| 24.0 MB 3.7 MB/s            
     |████████████████████████████████| 56 kB 3.1 MB/s            
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.3.2/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
#for text pre-processing
import re, string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
#for model-building
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
# bag of words
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#for word embedding
import gensim
from gensim.models import Word2Vec

[nltk_data] Downloading package punkt to /Users/juliette/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/juliette/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/juliette/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [23]:
df_train = pd.read_json("train.jsonl",lines=True)
df_test = pd.read_json("test.jsonl",lines=True)
df_dev = pd.read_json("dev.jsonl",lines=True)

In [24]:
df_train.head()

id            img  label  \
0  42953  img/42953.png      0   
1  23058  img/23058.png      0   
2  13894  img/13894.png      0   
3  37408  img/37408.png      0   
4  82403  img/82403.png      0   

                                                text  
0   its their character not their color that matters  
1  don't be afraid to love again everyone is not ...  
2                           putting bows on your pet  
3  i love everything and everybody! except for sq...  
4  everybody loves chocolate chip cookies, even h...

# EDA

In [25]:
#Distribution : 
x=df_train['label'].value_counts()
print(x)

0    5450
1    3050
Name: label, dtype: int64


Il y a 5450 memes non haineux et 3050 memes haineux

In [26]:
# Vérification des NA
df_train.isna().sum()

id       0
img      0
label    0
text     0
dtype: int64

Il n'y a aucune valeur manquante

In [27]:
# Nombre de mots 

df_train['word_count'] = df_train['text'].apply(lambda x: len(str(x).split()))
print(df_train[df_train['label']==1]['word_count'].mean()) # memes haineux
print(df_train[df_train['label']==0]['word_count'].mean()) # memes non haineux

12.79344262295082
11.154495412844037


Il y a environ le même nombre de mots entre les deux types de même (en moyenne un de plus pour les mêmes haineux)

In [28]:
# Nombre de lettres
df_train['char_count'] = df_train['text'].apply(lambda x: len(str(x)))
print(df_train[df_train['label']==1]['char_count'].mean()) #memes haineux
print(df_train[df_train['label']==0]['char_count'].mean()) #memes non haineux

68.48360655737704
58.489724770642205


Il y a environ une dizaine de caractères en plus dans les mêmes haineux

# Preparation de la base avant la classification

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliette/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
#On enlève la ponctuatoin et les strips
def preprocess(text):
    text = text.lower() 
    text=text.strip()  #suppression des caractères de tête et de queue
    text=re.compile('<.*?>').sub('', text) 
    text = re.compile('[%s]' % re.escape(string.punctuation)).sub(' ', text)  
    text = re.sub('\s+', ' ', text)  
    text = re.sub(r'\[[0-9]*\]',' ',text) 
    text=re.sub(r'[^\w\s]', '', str(text).lower().strip())
    text = re.sub(r'\d',' ',text) 
    text = re.sub(r'\s+',' ',text) 
    return text

 
# STOPWORD REMOVAL : on enlève les mots inutiles "the" etc.
def stopword(string):
    a= [i for i in string.split() if i not in stopwords.words('english')]
    return ' '.join(a)

#LEMMATIZATION 
# On initialise le lemmatizer
wl = WordNetLemmatizer()
 
# This is a helper function to map NTLK position tags

#WordNetLemmatizer a besoin des balises Pos pour comprendre si le mot est un nom, 
#un verbe, un adjectif, etc. Par défaut, elle est définie sur Noun

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# Tokenize 
def lemmatizer(string):
    word_pos_tags = nltk.pos_tag(word_tokenize(string)) # Get position tags
    a=[wl.lemmatize(tag[0], get_wordnet_pos(tag[1])) for idx, tag in enumerate(word_pos_tags)] # Map the position tag and lemmatize the word/token
    return " ".join(a)



In [31]:
def finalpreprocess(string):
    return lemmatizer(stopword(preprocess(string)))
df_train['clean_text'] = df_train['text'].apply(lambda x: finalpreprocess(x))
df_test['clean_text'] = df_test['text'].apply(lambda x: finalpreprocess(x))
df_train.head()

id            img  label  \
0  42953  img/42953.png      0   
1  23058  img/23058.png      0   
2  13894  img/13894.png      0   
3  37408  img/37408.png      0   
4  82403  img/82403.png      0   

                                                text  word_count  char_count  \
0   its their character not their color that matters           8          48   
1  don't be afraid to love again everyone is not ...          12          58   
2                           putting bows on your pet           5          24   
3  i love everything and everybody! except for sq...          11          70   
4  everybody loves chocolate chip cookies, even h...           7          51   

                                          clean_text  
0                             character color matter  
1                       afraid love everyone like ex  
2                                        put bow pet  
3  love everything everybody except squirrel hate...  
4    everybody love chocolate chip cooky even hitler

In [32]:
# Mise en vecteur (word embedding)

#SPLITTING le TRAINING DATASET EN UN TRAIN ET UN TEST
X_train, X_test, y_train, y_test = train_test_split(df_train["clean_text"],df_train["label"],test_size=0.2,shuffle=True)

#X contient les mots et y contient les labels correspondants



In [33]:
print(X_test.head())
print(y_test.head())

6306      call islamphobe give sharia law
8035                     perfect girl exi
4808    play stupid game win stupid prize
7435         rather push chevy drive ford
2144                  people protect blue
Name: clean_text, dtype: object
6306    1
8035    1
4808    0
7435    0
2144    0
Name: label, dtype: int64


In [34]:
#Tf-Idf (méthode pour mathématiser le texte)
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
X_train_vectors_tfidf = tfidf_vectorizer.fit_transform(X_train) # on obtient des matrices
X_test_vectors_tfidf = tfidf_vectorizer.transform(X_test)

# Classification

## Régression linéaire

In [36]:
#FITTING THE CLASSIFICATION MODEL using Logistic Regression(tf-idf)
lr_tfidf=LogisticRegression(solver = 'liblinear', C=10, penalty = 'l2')
lr_tfidf.fit(X_train_vectors_tfidf, y_train)  

#Predict y value for test dataset
y_predict = lr_tfidf.predict(X_test_vectors_tfidf)
y_prob = lr_tfidf.predict_proba(X_test_vectors_tfidf)[:,1]
print(classification_report(y_test,y_predict))
print('Confusion Matrix:',confusion_matrix(y_test, y_predict))
 
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)
print('AUC:', roc_auc)

              precision    recall  f1-score   support

           0       0.71      0.78      0.74      1096
           1       0.51      0.41      0.45       604

    accuracy                           0.65      1700
   macro avg       0.61      0.59      0.60      1700
weighted avg       0.63      0.65      0.64      1700

Confusion Matrix: [[854 242]
 [356 248]]
AUC: 0.6548443769033692


Interprétation : 

   La précision : 
   
Sur l'ensemble des memes que le modèle à prédit comme non haineux (label 1) seuls 51% le sont
Sur l'ensemble des memes que le modèle à prédit comme haineux (label 0), 71% le sont
            
   Le Recall : 
   
Sur l'ensemble des memes qui sont non haineux, le modèle n'a prédit ce résultat correctement que pour 41% d'entre eux.
Sur l ensemble des memes qui sont haineux, le modèle a prédit ce résultat correctement que pour 78% d'entre eux.
      

Une accuracy de 0,65.

CCl : Mauvaise prédiction pour les memes non haineux. 

## Naive Bayes Classifier Algorithm

In [38]:
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score


In [43]:
# fit the training dataset on the NB classifier

Naive = naive_bayes.MultinomialNB()
Naive.fit(X_train_vectors_tfidf,y_train)

# predict the labels on validation dataset

predictions_NB = Naive.predict(X_test_vectors_tfidf)


#classification report
print(classification_report(y_test,predictions_NB))

# Accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, y_test))

              precision    recall  f1-score   support

           0       0.66      0.92      0.77      1096
           1       0.53      0.16      0.24       604

    accuracy                           0.65      1700
   macro avg       0.60      0.54      0.51      1700
weighted avg       0.62      0.65      0.58      1700

Naive Bayes Accuracy Score ->  0.6505882352941177


On retrouve une accuracy de 0.65 et des prédictions plus au moins similaire dans le sens où il y a de bonnes prédictions pour les memes haineux mais de mauvaises pedictions pour les memes non haineux.

## SVM — Support Vector Machine

In [46]:
# fit the training dataset on the classifier

SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(X_train_vectors_tfidf,y_train)

# predict the labels on validation dataset

predictions_SVM = SVM.predict(X_test_vectors_tfidf)

#classification report
print(classification_report(y_test,predictions_SVM))

# Use accuracy_score function to get the accuracy

print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, y_test))

              precision    recall  f1-score   support

           0       0.72      0.87      0.79      1096
           1       0.63      0.39      0.48       604

    accuracy                           0.70      1700
   macro avg       0.68      0.63      0.64      1700
weighted avg       0.69      0.70      0.68      1700

SVM Accuracy Score ->  0.701764705882353


On obtient une meilleure accuracy : 0.7. 
Au vue des autres résultats, on obient les mêmes conclusions que précédement. 